### ISSUE TITLE
Add QA for P(k)

### ISSUE THREAD

**Issue by londumas** [igmhub/desi_QA#14]
Add QA for P(k)

**Comment by londumas** [comment]
@Waelthus, Thank you very much for the work. I didn't realized that I gave you writing access.
It is important that others do review of our work before merging.
Could you add the DR9 data fitting functions to the different P(k) plots so that we can compare to them and see where the mocks are failing.

**Comment by Waelthus** [comment]
Sure, adding the lines to the plot shouldn't be an issue. Sorry for the mess with the pull request. 

Am 20. November 2018 16:15:34 MEZ schrieb "Hélion du Mas des Bourboux" <notifications@github.com>:
>@Waelthus, Thank you very much for the work. I didn't realized that I
>gave you writing access.
>It is important that others do review of our work before merging.
>Could you add the DR9 data fitting functions to the different P(k)
>plots so that we can compare to them and see where the mocks are
>failing.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/igmhub/desi_QA/issues/14#issuecomment-440308855

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by londumas** [comment]
fixed via https://github.com/igmhub/desi_QA/pull/18.
Thank you @Waelthus
